### ISSUE TITLE
Any job has been see in Octane interface

### ISSUE THREAD

**Issue by yann696** [MicroFocus/octane-gitlab-service#32]
Hello, 

When I try to create a pipeline in the Octane interface,  with this new version of the bridge, no jobs is found. 

![image](https://user-images.githubusercontent.com/77964270/105692504-c84b1500-5efe-11eb-9fa7-a33b1002e6f2.png)
[](url)

However, my server (octane-gitlab-service-1.1.93.jar) is well detected. 

When octane-gitlab-service-1.1.93.jar starts, I have this error message : 

2021-01-25 10:46:35,109 main ERROR RollingFile contains an invalid element or attribute "NoMarkerFilter"
2021-01-25 10:46:35,450 main ERROR RollingFile contains an invalid element or attribute "NoMarkerFilter"

However, the service starts. I send the full trace when the service starts: 

pnjn1805@yd-CZC0329TKC:~/octane$ sudo systemctl status octane.service
● octane.service - Octane-Gitlab Bridge
     Loaded: loaded (/etc/systemd/system/octane.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2021-01-25 10:46:34 CET; 23min ago
   Main PID: 1528661 (start_octane.sh)
      Tasks: 89 (limit: 56314)
     Memory: 1.0G
     CGroup: /system.slice/octane.service
             ├─1528661 /bin/sh /home/pnjn1805/octane/start_octane.sh
             ├─1528667 sudo java8 -jar octane-gitlab-service-1.1.93.jar
             └─1528675 java8 -jar octane-gitlab-service-1.1.93.jar

Jan 25 10:46:35 yd-CZC0329TKC start_octane.sh[1528675]: 2021-01-25 10:46:35,109 main ERROR RollingFile contains an invalid element or attribute "NoMarkerFilter"
Jan 25 10:46:35 yd-CZC0329TKC start_octane.sh[1528675]: 2021-01-25 10:46:35,450 main ERROR RollingFile contains an invalid element or attribute "NoMarkerFilter"
Jan 25 10:46:35 yd-CZC0329TKC start_octane.sh[1528675]:   .   ____          _            __ _ _
Jan 25 10:46:35 yd-CZC0329TKC start_octane.sh[1528675]:  /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
Jan 25 10:46:35 yd-CZC0329TKC start_octane.sh[1528675]: ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
Jan 25 10:46:35 yd-CZC0329TKC start_octane.sh[1528675]:  \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
Jan 25 10:46:35 yd-CZC0329TKC start_octane.sh[1528675]:   '  |____| .__|_| |_|_| |_\__, | / / / /
Jan 25 10:46:35 yd-CZC0329TKC start_octane.sh[1528675]:  =========|_|==============|___/=/_/_/_/
Jan 25 10:46:35 yd-CZC0329TKC start_octane.sh[1528675]:  :: Spring Boot ::        (v2.0.3.RELEASE)
Jan 25 10:46:47 yd-CZC0329TKC start_octane.sh[1528675]: Connection to Octane was successful. gitlab application is ready...

More over, in the nga.log I have a new permission issue: 
25/01/2021 10:51:14,501 WARN  [AbridgedTasksWorker-106                           ] OctaneServices                  : IMPORTANT: The integration user has no project member permissions

**Comment by lazara3** [comment]
Hi, 
The error means that your user has a DEVELOPER or REPORTER permission.  
In order to fix it do the following steps:
1. login to GitLab with user that have a **maintainer**  or **owner** permissions
2. create an access token with all permission
3. update the properties file in the service with the new access token you created
4. restart the service.
let me know if it still don't work for you..

**Comment by yann696** [comment]
I am already owner on this project: 
![image](https://user-images.githubusercontent.com/77964270/105850534-23a20380-5fe2-11eb-8848-9c86db4dd469.png)

And also, my token is a personal token with all the rights: 
![image](https://user-images.githubusercontent.com/77964270/105850728-6532ae80-5fe2-11eb-960f-17783fee6bbb.png)

**Comment by lazara3** [comment]
Hi
I opened an internal defect on the issue I found:
code problem: using Integer == Integer instead of Integer.equals(Obj)

It happen only if you have an user's id greater then 127..
this is why it happen only on env with many users.

**Comment by lazara3** [comment]
fixed
