### ISSUE TITLE
Neccessary Permissions for the Octane and Gitlab API Access?

### ISSUE THREAD

**Issue by derandiunddasbo** [MicroFocus/octane-gitlab-service#59]
There's no detailed information in the documentation regarding neccessary permissions for the Octane API access Client ID and for the GitLab personal access token. Which permissions are needed for the service to work?

**Comment by lazara3** [comment]
Hi,
You can find  [here](https://admhelp.microfocus.com/octane/en/16.0.100-16.0.200/Online/Content/AdminGuide/article_CI_servers_setup.htm?Highlight=setup%20plugin) the details about Octane API access.
 In general, The access keys must be assigned the CI/CD Integration role in all relevant workspaces
 
 In GitLab : 
 The scope of the access token should be "api". 
 And the user should be able to see all projects you want to see in Octane
