### ISSUE TITLE
Configuration options not matching in the applicaton.properties example and the description

### ISSUE THREAD

**Issue by derandiunddasbo** [MicroFocus/octane-gitlab-service#60]
There are four gitlab.mergeRequests.variables.* config options in the example, but in the description they seem to have different names. Which of them are the correct ones?

Example config vs. description:

gitlab.mergeRequests.variables.publishMergeRequestVarName vs. gitlab.variables.publishMergeRequestVarName
gitlab.mergeRequests.variables.destinationWorkspaceVarName vs. gitlab.variables.destinationWorkspaceVarName
gitlab.mergeRequests.variables.useSSHFormatVarName vs. gitlab.variables.useSSHFormatVarName
gitlab.mergeRequests.mergeRequestHistoryFolderPath vs. gitlab.mergeRequestHistoryFolderPath

**Comment by lazara3** [comment]
Hi,
Thanks for the review.
The correct name is with "*.mergeRequests.*" , The readme file has been updated
